# Generated by Django 6.0.4 on 2026-04-29 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='текст вопроса')),
                ('explanation', models.TextField(blank=True, verbose_name='объяснение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['scene', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='session key')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='сложность')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='всего вопросов')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='правильных ответов')),
                ('scenes_completed', models.PositiveIntegerField(default=0, verbose_name='пройдено сцен')),
                ('is_finished', models.BooleanField(default=False, verbose_name='завершено')),
                ('scene_order', models.JSONField(blank=True, default=list, verbose_name='порядок сцен')),
            ],
            options={
                'verbose_name': 'Сессия викторины',
                'verbose_name_plural': 'Сессии викторин',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название сцены')),
                ('historical_period', models.CharField(blank=True, max_length=120, verbose_name='период')),
                ('event_year', models.CharField(blank=True, max_length=32, verbose_name='год события')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='уровень')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenes/', verbose_name='панорамная картинка')),
                ('description', models.TextField(blank=True, verbose_name='описание сцены')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_interesting', models.BooleanField(default=False, verbose_name='интересно')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата фидбека')),
                ('quiz_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='quiz.quizsession', verbose_name='сессия')),
            ],
            options={
                'verbose_name': 'Фидбек',
                'verbose_name_plural': 'Фидбек',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.scene', verbose_name='сцена'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='правильно')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='отвечено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='вопрос')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizsession', verbose_name='сессия')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answeroption', verbose_name='выбранный ответ')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ['answered_at'],
            },
        ),
    ]
