# Generated by Django 6.0.4 on 2026-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='panorama_url',
            field=models.URLField(blank=True, help_text='URL equirectangular панорамы для интерактивного просмотра', verbose_name='URL панорамы 360°'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scenes/', verbose_name='обычная картинка'),
        ),
    ]
