# Generated by Django 6.0.4 on 2026-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_scene_panorama_url_alter_scene_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите equirectangular изображение для 360° панорамы', null=True, upload_to='scenes/', verbose_name='панорамное изображение'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='panorama_url',
            field=models.URLField(blank=True, help_text='Внешний URL equirectangular панорамы (имеет приоритет над загруженным изображением)', verbose_name='URL панорамы 360°'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='quiz_single_correct_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('quiz_session', 'question'), name='quiz_unique_user_answer_per_question'),
        ),
    ]
